#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================
# All SpaceVim option below [option] section
[options]

    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme layer
    colorscheme = "gruvbox"
    # colorscheme = "nord"
    colorscheme_bg = "dark"

    # Disable guicolors in basic mode, many terminal do not support 24bit true colors
    enable_guicolors = true

    # Disable statusline separator, if you want to use other value, please install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"

    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true   ### toggled by me: default is false
    relativenumber = true

    # guifont = "SauceCodePro Nerd Font Mono:h11"     ### useless option setting for terminal mode
    # Note: need to set Terminator font to not use system font &&
    # NOTE: can use specific ones such as SauceCodePro, UbuntuMono, Hack, Inconsolata, etc.

    # custom_plugins = [['tpope/vim-rhubarb'],['tpope/vim-eunuch'], ['dahu/vimple'], ['AndrewRadev/linediff.vim'],['takac/vim-hardtime']]

    ### Options Set by Me
    window_smartclose = ""
    filemanager = "defx"    # use Shougo's defx to manage files
    search_tools = ['rg']   # only use rg for grepping (both Grepper & FlyGrep)
    windows_leader = ''     # remove top-level Window prefix 's' for time being, b/c of vim-sneak (& vim-surround?)

    bootstrap_before = "my_config#before"
    bootstrap_after = "my_config#after"

    # default is true; see .SpaceVim/autoload/SpaceVim/plugins/projectmanager.vim for implementationg
    project_rooter_automatically = true   ### CtrlSpace can also manage CWD



# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30



### Layers Added by Me

# [[layers]]
  # name = "lang#c"

[[layers]]
  name = "lang#lua"
  foldmethod = "manual"
  # foldmethod = 'expr' ### needs foldexpr function's extreme slowness fixed before using

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#scheme"
  dialect = "guile"

[[layers]]
  name = "lang#vim"

# [[layers]]
  # name = "fzf"

# [[layers]]
  # name = "format"

# [[layers]]
  # name = "indentmove"

# [[layers]]
  # name = "VersionControl"

[[layers]]
  name = "git"
  git-plugin = "fugitive"

[[layers]]
  name = "github"

[[layers]]
  name = "edit"

[[layers]]
  name = "sudo"

[[layers]]
  name = "ui"

[[layers]]
  name = "tools"

[[layers]]
  name = "tools#zeal"

[[layers]]
  name = "incsearch"

[[layers]]
 name = "ctrlspace"
 # home-mapping-key = "<C-p>"
 # autosave-workspaces = true
 # autoload-workspaces = false
 # enable-spacevim-styled-keys = false

# [[layers]]
  # name = "tmux"



# TODO: can use `[[custom_plugins]]`
